# Generated by Django 4.2.5 on 2024-11-26 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personel_personelgiris_remove_entrytime_entry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrytime',
            name='employee',
        ),
        migrations.AddField(
            model_name='entrytime',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entrytime',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='name',
            field=models.CharField(default='Default Name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
