# Generated by Django 4.2.5 on 2024-11-26 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_entrytime_employee_entrytime_entry_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryTime',
        ),
        migrations.DeleteModel(
            name='Personel',
        ),
        migrations.DeleteModel(
            name='PersonelGiris',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employeedetails'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
