# Generated by Django 5.1.3 on 2024-11-26 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_entrytime_delete_personel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.employeedetails'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], default='Full Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='app.employeedetails'),
        ),
    ]
