# Generated by Django 5.1.3 on 2024-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_latenessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
